FROM amazoncorretto:11

# Set the working directory
WORKDIR /app

# Copy the pre-built jar file
COPY prototype-0.0.1-SNAPSHOT-jar-with-dependencies.jar .

# Run the application
CMD ["java", "-jar", "prototype-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]

